set nocompatible
set number
syntax on
filetype on
filetype indent on
filetype plugin on
set guifont=Consolas:h12:cANSI
set ignorecase
set incsearch
set hlsearch
set hidden
set cursorline

highlight CursorLine guibg=#ffffcc ctermbg=white

set statusline=
set statusline +=%1*\ %n\ %*            "buffer number
set statusline +=%5*%{&ff}%*            "file format
set statusline +=%3*%y%*                "file type
set statusline +=%4*\ %<%F%*            "full path
set statusline +=%2*%m%*                "modified flag
set statusline +=%1*%=%5l%*             "current line
set statusline +=%2*/%L%*               "total lines
set statusline +=%1*%4v\ %*             "virtual column number
set statusline +=%2*0x%04B\ %*          "character under cursor
