set nocompatible                        " Lose compatability with original vi
set number                              " Show lines numbers
syntax on                               " Enable syntax highlighting
filetype on                             " Enable file type detection
filetype indent on                      " Enable indenting based on filetype
filetype plugin on                      " Enable plugins based on filetype
set guifont=Consolas:h12:cANSI          " Nice GUI font for gvim
set textwidth=0                         " Disable automatic insertion of EOL characters
set ignorecase                          " Ignore case in searches
set smartcase                           " Don't ignore case if search pattern contains upper case characters
set incsearch                           " Show matches as search patttern is typed
set hlsearch                            " Highlight search matches
set hidden                              " Hide (don't unload) buffer when opening another buffer
set cursorline                          " Enable highlighting of current line

highlight CursorLine guibg=#ffffcc ctermbg=white

set statusline=                         " Clear statusline
set statusline +=%1*\ %n\ %*            " buffer number
set statusline +=%5*%{&ff}%*            " file format
set statusline +=%3*%y%*                " file type
set statusline +=%4*\ %<%F%*            " full path
set statusline +=%2*%m%*                " modified flag
set statusline +=%1*%=%5l%*             " current line
set statusline +=%2*/%L%*               " total lines
set statusline +=%1*%4v\ %*             " virtual column number
set statusline +=%2*0x%04B\ %*          " character under cursor

set backspace=indent,start,eol          " Allow backspace over most things
set wildmenu                            " Show menu of options when tab is pressed
set laststatus=2                        " Always show status line

set noexrc                              " Disallow reading of .*rc files in current directory

set wrap                                " Cause long lines to wrap
set linebreak                           " Wrap lines at word breaks (not just at max characters)

let mapleader=","                       " Change the leader key to comma (,)

nnoremap <silent> <leader>ww :set wrap!<cr>      " Toggle wrapping of long lines

nnoremap <silent> <leader>ev :e $MYVIMRC<cr>     " Edit vimrc
nnoremap <silent> <leader>sv :so $MYVIMRC<cr>    " Reload (source) vimrc
nnoremap <silent> <leader>nh :nohlsearch<cr>     " Switch off search highlighting







" this statusline colouring stuff works - not sure why previous stuff does not - need to investigate

set statusline=%t\ %m%r%y%=(ascii=\%03.3b,hex=\%02.2B)\ (%l/%L,%c)\ (%P)
set laststatus=2
" change highlighting based on mode
if version >= 700
  highlight statusLine cterm=bold ctermfg=black ctermbg=red gui=bold guifg=black guibg=red
  au InsertLeave * highlight StatusLine cterm=bold ctermfg=black ctermbg=red gui=bold guifg=black guibg=red
  au InsertEnter * highlight StatusLine cterm=bold ctermfg=black ctermbg=green gui=bold guifg=black guibg=green
endif

